apiVersion: codeenginestudio/v1
kind: Component
metadata:
  name: Spring MVC
  description: |
    Java web example
  links:
    - title: Code check
      url: https://sonarqube.devlake.codeenginestudio.com/
spec:
  type: library
  owner: Huy Nguyen
  lifecycle: experimental